# Generated by Django 3.2.8 on 2026-02-17 15:44

import career_app.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField(blank=True)),
                ('required_skills', career_app.fields.JSONTextField(default=list)),
                ('optional_skills', career_app.fields.JSONTextField(default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='JobListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('company', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('role_slug', models.CharField(blank=True, max_length=100)),
                ('skills_required', career_app.fields.JSONTextField(default=list)),
                ('url', models.URLField(blank=True)),
                ('posted_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-posted_date'],
            },
        ),
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('resource_type', models.CharField(max_length=20)),
                ('title', models.CharField(max_length=300)),
                ('url', models.URLField(blank=True)),
                ('source', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['skill_name', 'resource_type'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('raw_text', models.TextField(blank=True)),
                ('skills', career_app.fields.JSONTextField(default=list)),
                ('education', career_app.fields.JSONTextField(default=list)),
                ('experience', career_app.fields.JSONTextField(default=list)),
                ('predicted_roles', career_app.fields.JSONTextField(default=list)),
                ('skill_gaps', career_app.fields.JSONTextField(default=list)),
                ('skill_score', models.FloatField(default=0.0)),
                ('career_readiness', models.CharField(blank=True, max_length=50)),
                ('learning_recommendations', career_app.fields.JSONTextField(default=list)),
                ('session_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('aliases', career_app.fields.JSONTextField(blank=True, default=list)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
