# Generated by Django 3.2.8 on 2026-03-22 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('career_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='joblisting',
            name='url',
            field=models.URLField(blank=True, max_length=512),
        ),
    ]
